apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-maven-build
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:swethakanuri/Opsera-maven-build.git
    targetRevision: main  # Change this to the correct branch if needed
    path: k8s  # Change this to the correct directory where manifests are stored
  destination:
    server: https://kubernetes.default.svc
    namespace: opsera
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
CreateNamespace=true
